import { CartProvider } from "../_components/CartContext";

export const metadata = {
  title: "TubVilla - Order successful!",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
