function FAQList() {
  return (
    <section className="mt-16 border-t border-stone-200 pt-12 mb-16">
      {/* Section Heading */}
      <div className="mb-8">
        <h2 className="text-2xl font-black tracking-tight text-stone-950 sm:text-3xl">
          Frequently Asked Questions
        </h2>
        <p className="mt-2 text-sm text-stone-600">
          Everything you need to know about setting up and enjoying your
          levitating display.
        </p>
      </div>

      {/* FAQ Accordion List */}
      <div className="space-y-4">
        {/* Question 1 */}
        <div className="rounded-2xl border border-stone-200 bg-white p-5 sm:p-6">
          <details className="group">
            <summary className="flex cursor-pointer items-center justify-between list-none">
              <span className="font-bold text-stone-950 sm:text-lg">
                How does the car float?
              </span>
              <span className="transition group-open:rotate-180 text-stone-500">
                <svg
                  className="h-5 w-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth="2.5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </span>
            </summary>
            <div className="mt-4 text-sm leading-6 text-stone-600 border-t border-stone-100 pt-3">
              The display utilizes advanced electromagnetic suspension
              technology. The premium base plugs into a standard wall outlet,
              creating an upward magnetic force that perfectly balances the
              weight of the car, allowing it to suspend and spin completely
              friction-free in mid-air.
            </div>
          </details>
        </div>

        {/* Question 2 */}
        <div className="rounded-2xl border border-stone-200 bg-white p-5 sm:p-6">
          <details className="group">
            <summary className="flex cursor-pointer items-center justify-between list-none">
              <span className="font-bold text-stone-950 sm:text-lg">
                What happens if the power goes out or gets unplugged?
              </span>
              <span className="transition group-open:rotate-180 text-stone-500">
                <svg
                  className="h-5 w-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth="2.5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </span>
            </summary>
            <div className="mt-4 text-sm leading-6 text-stone-600 border-t border-stone-100 pt-3">
              We built this with a built-in failsafe protection mechanism. If
              the base loses power or is accidentally shut off, the internal
              safety magnets instantly pull the car down securely to the base.
              The car will never fall, drop, or slide off your desk.
            </div>
          </details>
        </div>

        {/* Question 3 */}
        <div className="rounded-2xl border border-stone-200 bg-white p-5 sm:p-6">
          <details className="group">
            <summary className="flex cursor-pointer items-center justify-between list-none">
              <span className="font-bold text-stone-950 sm:text-lg">
                Does the car require batteries?
              </span>
              <span className="transition group-open:rotate-180 text-stone-500">
                <svg
                  className="h-5 w-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth="2.5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </span>
            </summary>
            <div className="mt-4 text-sm leading-6 text-stone-600 border-t border-stone-100 pt-3">
              No, the car itself does not require any batteries or charging. The
              energy needed for both the continuous suspension and the glowing
              LED headlights is drawn entirely from the electromagnetic field
              generated by the plugged-in base.
            </div>
          </details>
        </div>

        {/* Question 4 */}
        <div className="rounded-2xl border border-stone-200 bg-white p-5 sm:p-6">
          <details className="group">
            <summary className="flex cursor-pointer items-center justify-between list-none">
              <span className="font-bold text-stone-950 sm:text-lg">
                Is it difficult to set up and balance?
              </span>
              <span className="transition group-open:rotate-180 text-stone-500">
                <svg
                  className="h-5 w-5"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  strokeWidth="2.5"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M19 9l-7 7-7-7"
                  />
                </svg>
              </span>
            </summary>
            <div className="mt-4 text-sm leading-6 text-stone-600 border-t border-stone-100 pt-3">
              Not at all. Every display comes with a simple, step-by-step
              instruction guide. It typically takes less than 60 seconds to find
              the magnetic sweet spot on your first try. Once balanced, it will
              float and spin indefinitely until you turn it off.
            </div>
          </details>
        </div>
      </div>
    </section>
  );
}
export default FAQList;
